# Generated by Django 3.0.5 on 2020-04-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('conta_dsc', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.IntegerField()),
                ('pago', models.BooleanField()),
                ('tipo_id', models.IntegerField()),
                ('usuario', models.CharField(max_length=200)),
            ],
        ),
    ]
