# Generated by Django 3.1.4 on 2021-02-03 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('observacao', models.CharField(max_length=1000)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=300)),
                ('outra_midia', models.CharField(max_length=300)),
                ('observacao', models.CharField(max_length=1000)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('estabelecimento_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('em_estoque', models.CharField(max_length=1)),
                ('medida', models.CharField(max_length=100)),
                ('unidade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observacao', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(upload_to=None)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.categoria')),
                ('estabelecimento_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.estabelecimento')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='estabelecimento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cardapio.estabelecimento'),
        ),
    ]
