# Generated by Django 3.1.3 on 2021-01-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeja', '0002_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='tipo_id',
            new_name='tipo',
        ),
    ]
