# Generated by Django 3.1.4 on 2021-03-10 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='fotos/treino')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'exercicio',
                'verbose_name_plural': 'exercicios',
            },
        ),
        migrations.CreateModel(
            name='Grupo_muscular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'grupo_muscular',
                'verbose_name_plural': 'grupo_musculars',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treino.plano')),
            ],
            options={
                'verbose_name': 'treino',
                'verbose_name_plural': 'treinos',
            },
        ),
        migrations.CreateModel(
            name='Treino_exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.DecimalField(decimal_places=2, max_digits=4)),
                ('repetições', models.IntegerField()),
                ('feito', models.IntegerField()),
                ('data_hora_feito', models.DateTimeField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treino.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treino.treino')),
            ],
            options={
                'verbose_name': 'treino_exercicio',
                'verbose_name_plural': 'treino_exercicios',
            },
        ),
        migrations.AddField(
            model_name='exercicio',
            name='grupo_muscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treino.grupo_muscular'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
