# Generated by Django 3.2.5 on 2021-07-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0002_auto_20210317_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino_exercicio',
            old_name='data_hora_feito',
            new_name='data_hora',
        ),
        migrations.RemoveField(
            model_name='treino_exercicio',
            name='feito',
        ),
    ]
