# Generated by Django 3.1.4 on 2021-03-10 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_pagamento', models.DateTimeField()),
                ('moeda', models.CharField(max_length=100)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'gastos',
                'verbose_name_plural': 'gastoss',
            },
        ),
        migrations.CreateModel(
            name='Mala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mala',
                'verbose_name_plural': 'malas',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'viagem',
                'verbose_name_plural': 'viagems',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=100)),
                ('data_saida', models.DateTimeField()),
                ('data_chegada', models.DateTimeField()),
                ('local_saida', models.CharField(max_length=100)),
                ('local_chegada', models.CharField(max_length=100)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.gasto')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.viagem')),
            ],
            options={
                'verbose_name': 'transporte',
                'verbose_name_plural': 'transportes',
            },
        ),
        migrations.CreateModel(
            name='Tipo_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('consumo', models.CharField(max_length=100)),
                ('mala', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.mala')),
            ],
            options={
                'verbose_name': 'tipo_item',
                'verbose_name_plural': 'tipo_items',
            },
        ),
        migrations.CreateModel(
            name='Tipo_gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.viagem')),
            ],
            options={
                'verbose_name': 'tipo_gasto',
                'verbose_name_plural': 'tipo_gastos',
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.viagem')),
            ],
            options={
                'verbose_name': 'roteiro',
                'verbose_name_plural': 'roteiros',
            },
        ),
        migrations.AddField(
            model_name='mala',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.viagem'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('mala', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.mala')),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.tipo_item')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.gasto')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.viagem')),
            ],
            options={
                'verbose_name': 'hospedagem',
                'verbose_name_plural': 'hospedagems',
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.tipo_gasto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.viagem'),
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='fotos/viajei')),
                ('data', models.DateTimeField()),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.album')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('observacao', models.CharField(max_length=100)),
                ('feito', models.CharField(max_length=100)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.gasto')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.roteiro')),
            ],
            options={
                'verbose_name': 'atracao',
                'verbose_name_plural': 'atracaos',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.viagem'),
        ),
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viajei.viagem')),
            ],
            options={
                'verbose_name': 'acompanhante',
                'verbose_name_plural': 'acompanhantes',
            },
        ),
    ]
