# Generated by Django 3.1.4 on 2021-03-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atracao',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='observacao',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporte',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
