# Generated by Django 2.2.5 on 2020-07-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investe.Empresa'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
