# Generated by Django 2.2.5 on 2020-07-23 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investe', '0002_auto_20200723_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='data',
        ),
        migrations.AddField(
            model_name='ordem',
            name='datatime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
