# Generated by Django 2.2.5 on 2020-07-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investe', '0003_auto_20200723_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordem',
            old_name='datatime',
            new_name='data',
        ),
    ]
